spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        enable.idempotence: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    try-it-out-enabled: true
    filter: true
  group-configs:
    - group: 'user-service'
      display-name: 'User Service API'
      paths-to-match: '/api/**'

springwolf:
  docket:
    base-package: com.example.userservice.service
    info:
      title: ${spring.application.name}
      version: 1.0.0
    servers:
      kafka-server:
        protocol: kafka
        host: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
  plugin:
    kafka:
      publishing:
        enabled: true
        producer:
          bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9091,localhost:9092,localhost:9094}
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            acks: all
            enable.idempotence: true
